environments:
  general:
    KODOK_HTTP_PORT: 3011
    KODOK_EVENT: kodok
  services: {}

components:
  kodok:
    type: service
    origin: "" # fill this one with your git repository
    branch: master
    location: "."
    start: npm install && npm start

