environments:
  general:
    SIPUT_HTTP_PORT: 3012
    SIPUT_EVENT: siput
  services: {}

components:
  siput:
    type: service
    origin: "" # fill this one with your git repository
    branch: master
    location: "."
    start: npm install && npm start

