environments: 
  general:
    RMQ_HOST: 0.0.0.0
    RMQ_PORT: 5672
    RMQ_USER: root
    RMQ_PASSWORD: toor
    RMQ_VHOST: /

components: 
  myproject-rmq:
    type: container
    run: docker run --name "myproject-rmq" -e RABBITMQ_DEFAULT_USER=root -e RABBITMQ_DEFAULT_PASS=toor -p 5672:5672 -p 15672:15672 -d rabbitmq:3-management
    containerName: myproject-rmq

executions: 
  - myproject-rmq
  - kodok
  - siput
